# apps/src 用户自定义源文件（追加到根Makefile变量）

c_SRC_FILES += \
	apps/src/user_main.c \
	apps/src/gpio/gpio_cfg.c \
	apps/src/pa/pa_drv.c \
	apps/src/led_effect/led_effect.c \
	apps/src/key_handler/key_handler.c \

INCLUDES += \
	-Iapps/src \
	-Iapps/src/gpio \
	-Iapps/src/pa \
	-Iapps/src/led_effect \
	-Iapps/src/key_handler \
